[info]
name = brackets
[Func0]
fields = title,
func_name = replace
module = puddlestuff.functions
arguments = " )", ), False, False
[Func1]
fields = title,
func_name = replace
module = puddlestuff.functions
arguments = "( ", (, False, False
[Func2]
fields = title,
func_name = replace
module = puddlestuff.functions
arguments = " ]", ), False, False
[Func3]
fields = title,
func_name = replace
module = puddlestuff.functions
arguments = "[ ", (, False, False
[Func4]
fields = title,
func_name = replace
module = puddlestuff.functions
arguments = [, (, False, False
[Func5]
fields = title,
func_name = replace
module = puddlestuff.functions
arguments = ], ), False, False
[Func6]
fields = title,
func_name = replace
module = puddlestuff.functions
arguments = ~, (, False, False
[Func7]
fields = title,
func_name = replaceWithReg
module = puddlestuff.functions
arguments = \($, \), False
