[info]
name = return carriage
[Func0]
fields = comment,
func_name = replaceWithReg
module = puddlestuff.functions
arguments = \r, " ", False
[Func1]
fields = comment,
func_name = replaceWithReg
module = puddlestuff.functions
arguments = ^[^\"]+, "", False
