{
  "info": {
    "name": "split artist"
  }, 
  "Func0": {
    "fields": [
      "artist"
    ], 
    "arguments": [
      ", "
    ], 
    "module": "puddlestuff.functions", 
    "func_name": "split_by_sep"
  }
}